require:
  - solidus_dev_support/rubocop

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*

RSpec/NestedGroups:
  Max: 4

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false
